# Generated by Django 4.1.7 on 2023-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.FileField(upload_to='files/resource/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='files/thumbnail/'),
        ),
    ]
