# Generated by Django 4.1.7 on 2023-04-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_alter_payment_user_alter_usercourse_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('dicount', models.IntegerField(default=0)),
                ('expiredate', models.DateField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='sell.course')),
            ],
        ),
    ]
